language: go

go:
  - 1.9

env:
  global:
    - CC_TEST_REPORTER_ID=5b796f390a0a96b588373ca9a1fd5764ec2f84bc471a7533b8494e44f016215d

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

jobs:
  include:
    - env: TASK="lint"
      install: make install-tools
      script: make lint

    - env: TASK="test"
      install:
          - go get github.com/axw/gocov/gocov
      script: make test-ci

after_script:
  - ./cc-test-reporter after-build -t gocov --exit-code $TRAVIS_TEST_RESULT
